import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val annotation: String = "1.1.0"

  const val appcompat: String = "1.1.0"

  const val constraintlayout: String = "1.1.3"

  const val androidx_lifecycle: String = "2.2.0"

  const val recyclerview: String = "1.1.0"

  const val aapt2: String = "3.6.3-6040484"

  const val com_android_tools_build_gradle: String = "3.6.3"

  const val lint_gradle: String = "26.6.3"

  const val android_maven_gradle_plugin: String = "1.4.1" // available: "2.1"

  const val gson: String = "2.8.6"

  const val com_jakewharton_rxbinding3: String = "3.1.0"

  const val timber: String = "4.7.1"

  const val gradle_bintray_plugin: String = "1.8.4" // available: "1.8.5"

  const val ktlint: String = "0.34.2" // available: "0.36.0"

  const val com_squareup_retrofit2: String = "2.8.1"

  const val buildsrcversions: String = "0.4.2"

  const val rxandroid: String = "2.1.1"

  const val rxjava: String = "2.2.19"

  const val junit: String = "4.12" // available: "4.13"

  const val dokka_android_gradle_plugin: String = "0.9.18"

  const val org_jetbrains_kotlin: String = "1.3.72"

  const val org_koin: String = "2.1.5"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "6.4.1"

  const val gradleCurrentVersion: String = "5.6.4"
}
